steps:
  # Build and push frontend image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/peerprep-fe:$COMMIT_SHA",
        "--target",
        "production",
        "./peerprep-fe",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/peerprep-fe:$COMMIT_SHA",
      ]

  # Build and push question-service image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/question-svc:$COMMIT_SHA",
        "--target",
        "production",
        "./question-service",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/question-svc:$COMMIT_SHA",
      ]

  # Build and push user-service image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/user-svc:$COMMIT_SHA",
        "--target",
        "production",
        "./user-service",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/user-svc:$COMMIT_SHA",
      ]

  # Deploy to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes-manifests
      - --image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/peerprep-fe:$COMMIT_SHA,asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/question-svc:$COMMIT_SHA,asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/user-svc:$COMMIT_SHA
      - --location=asia-southeast1
      - --cluster=cs3219-g11-peerprep-kubes

  # Update the deployments to use the new images
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/peerprep-fe"
      - "peerprep-fe=asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/peerprep-fe:$COMMIT_SHA"
      - "deployment/question-service"
      - "question-service=asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/question-svc:$COMMIT_SHA"
      - "deployment/user-service"
      - "user-service=asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/user-svc:$COMMIT_SHA"
    env:
      - "CLOUDSDK_COMPUTE_ZONE=asia-southeast1"
      - "CLOUDSDK_CONTAINER_CLUSTER=cs3219-g11-peerprep-kubes"

options:
  dynamic_substitutions: true

images:
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/peerprep-fe:$COMMIT_SHA"
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/question-svc:$COMMIT_SHA"
  - "asia-southeast1-docker.pkg.dev/$PROJECT_ID/cs3219-g11-repo/user-svc:$COMMIT_SHA"
