services:
  redis-server:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379" # Expose Redis port
    networks:
      - peerprep-network
  frontend:
    image: asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/peerprep-fe:latest
    build:
      context: ./peerprep-fe
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./peerprep-fe:/app
      - ./peerprep-fe/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    networks:
      - peerprep-network
    env_file:
      - ./peerprep-fe/.env.production
  question-service:
    image: asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/question-svc:latest
    build:
      context: ./question-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./question-service:/app
      - ./question-service/node_modules:/app/node_modules
    ports:
      - "4001:4001"
    networks:
      - peerprep-network
    env_file:
      - ./question-service/.env.dev
  user-service:
    image: asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/user-svc:latest
    build:
      context: ./user-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./user-service:/app
      - ./user-service/node_modules:/app/node_modules
    ports:
      - "3001:3001"
    networks:
      - peerprep-network
    env_file:
      - ./user-service/.env
  matching-service:
    image: asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/matching-svc:latest
    build:
      context: ./matching-service
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./matching-service:/app
      - ./matching-service/node_modules:/app/node_modules
    ports:
      - "5001:5001"
    networks:
      - peerprep-network
    env_file:
      - ./matching-service/.env.dev
  # api-gateway:
  #   image: asia-southeast1-docker.pkg.dev/cs3219-g11-peerprep/cs3219-g11-repo/api-gateway:latest
  #   build:
  #     context: ./api-gateway
  #     dockerfile: Dockerfile
  #     target: development
  #   ports:
  #     - "8001:8001"
  #   networks:
  #     - peerprep-network
  #   env_file:
  #     - ./api-gateway/.env.dev
networks:
  peerprep-network:
    driver: bridge
