apiVersion: v1
kind: Secret
metadata:
  name: peerprep-config
type: Opaque
stringData:
  NEXT_PUBLIC_API_GATEWAY_URL: "${_NEXT_PUBLIC_API_GATEWAY_URL}"
  NEXT_PUBLIC_GITHUB_CLIENT_ID: "${_NEXT_PUBLIC_GITHUB_CLIENT_ID}"
  # Removed individual service URLs as they are no longer needed
