name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Trigger Cloud Build"
        env:
          NEXT_PUBLIC_QUESTION_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_QUESTION_SERVICE_URL }}
          NEXT_PUBLIC_AUTH_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_AUTH_SERVICE_URL }}
          NEXT_PUBLIC_USER_SERVICE_URL: ${{ secrets.NEXT_PUBLIC_USER_SERVICE_URL }}
          USER_SERVICE_URL: ${{ secrets.USER_SERVICE_URL }}
          QUESTION_SERVICE_URL: ${{ secrets.QUESTION_SERVICE_URL }}
        run: |
          gcloud builds submit --config cloudbuild.yaml \
            --substitutions _NEXT_PUBLIC_QUESTION_SERVICE_URL=$NEXT_PUBLIC_QUESTION_SERVICE_URL,_NEXT_PUBLIC_AUTH_SERVICE_URL=$NEXT_PUBLIC_AUTH_SERVICE_URL
