name: Deploy to GCP

on:
  push:
    branches:
      - feat/35-continuous-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Trigger Cloud Build
        run: |
          gcloud builds submit --config cloudbuild.yaml
